"""
node_interaction.py

Node interaction system for the dynamic overworld.

Subtypes generated by world.py:
  combat   → drone, guard, elite, boss
  challenge → puzzle, quiz, time_trial
  utility  → shop, healer, save_point
  event    → story, ambush, treasure
  hub      → base, crossroads, sanctuary (+ citadel)
"""

from backend.world import Node


def get_node_actions(node: Node) -> list[dict]:
    # ── Combat nodes ──────────────────────────────────────────────────────
    if node.type == "combat":
        actions = [
            {"id": "engage", "label": "⚔️ Engage", "type": "combat"},
            {"id": "study", "label": "📖 Study Enemy", "type": "info"},
        ]
        if node.subtype in ("elite", "boss"):
            actions.insert(1, {"id": "observe", "label": "👁️ Observe Weakness", "type": "info"})
        actions.append({"id": "leave", "label": "← Leave", "type": "navigation"})
        return actions

    # ── Challenge nodes ───────────────────────────────────────────────────
    if node.type == "challenge":
        if node.subtype == "puzzle":
            return [
                {"id": "investigate", "label": "🔍 Investigate", "type": "challenge"},
                {"id": "leave", "label": "← Leave", "type": "navigation"},
            ]
        if node.subtype == "quiz":
            return [
                {"id": "engage", "label": "📝 Take the Quiz", "type": "challenge"},
                {"id": "leave", "label": "← Leave", "type": "navigation"},
            ]
        if node.subtype == "time_trial":
            return [
                {"id": "engage", "label": "⏱️ Start Time Trial", "type": "challenge"},
                {"id": "leave", "label": "← Leave", "type": "navigation"},
            ]
        # fallback challenge
        return [
            {"id": "investigate", "label": "🔍 Investigate", "type": "challenge"},
            {"id": "leave", "label": "← Leave", "type": "navigation"},
        ]

    # ── Utility nodes ─────────────────────────────────────────────────────
    if node.type == "utility":
        if node.subtype == "healer":
            return [
                {"id": "rest", "label": "❤️ Rest & Heal", "type": "utility"},
                {"id": "leave", "label": "← Leave", "type": "navigation"},
            ]
        if node.subtype == "shop":
            return [
                {"id": "browse_shop", "label": "🛒 Browse Wares", "type": "utility"},
                {"id": "change_equipment", "label": "🔧 Change Equipment", "type": "utility"},
                {"id": "leave", "label": "← Leave", "type": "navigation"},
            ]
        if node.subtype == "save_point":
            return [
                {"id": "save", "label": "💾 Save Progress", "type": "utility"},
                {"id": "rest", "label": "❤️ Rest", "type": "utility"},
                {"id": "leave", "label": "← Leave", "type": "navigation"},
            ]
        return [
            {"id": "rest", "label": "❤️ Rest", "type": "utility"},
            {"id": "leave", "label": "← Leave", "type": "navigation"},
        ]

    # ── Event nodes ───────────────────────────────────────────────────────
    if node.type == "event":
        if node.subtype == "treasure":
            return [
                {"id": "open_chest", "label": "🎁 Open Chest", "type": "event"},
                {"id": "leave", "label": "← Leave", "type": "navigation"},
            ]
        if node.subtype == "ambush":
            return [
                {"id": "engage", "label": "⚔️ Fight!", "type": "combat"},
                {"id": "flee", "label": "🏃 Flee", "type": "navigation"},
            ]
        if node.subtype == "story":
            return [
                {"id": "listen", "label": "📜 Listen", "type": "event"},
                {"id": "leave", "label": "← Leave", "type": "navigation"},
            ]
        return [
            {"id": "investigate", "label": "🔍 Investigate", "type": "event"},
            {"id": "leave", "label": "← Leave", "type": "navigation"},
        ]

    # ── Hub nodes ─────────────────────────────────────────────────────────
    if node.type == "hub":
        actions = [
            {"id": "view_map", "label": "🗺️ View Map", "type": "info"},
            {"id": "rest", "label": "❤️ Rest", "type": "utility"},
        ]
        if node.subtype == "citadel":
            actions.insert(1, {"id": "change_equipment", "label": "🔧 Equipment", "type": "utility"})
            actions.insert(2, {"id": "view_codex", "label": "📕 Codex", "type": "info"})
        actions.append({"id": "leave", "label": "← Leave", "type": "navigation"})
        return actions

    # ── Fallback ──────────────────────────────────────────────────────────
    return [{"id": "leave", "label": "← Leave", "type": "navigation"}]
